- name: Test command on Batch Servers
  hosts: batch
  gather_facts: false
  become: true

  tasks:
    - name: Run test command
      ansible.builtin.shell: echo "Hello, World!" > /tmp/hello.txt
      
