# Playbookの名前（任意）を設定
- name: Test command on Batch Servers
  # 対象ホストグループ（inventory上の "batch" グループ）に対して実行
  hosts: batch
  # OS情報やネットワーク情報の取得をスキップ（軽量化のため）
  gather_facts: false
  # タスク実行時にsudo（root権限）を使用
  become: true

  roles:
    - cloudwatch_agent
